### PR TITLE
v2.2.0.0: bug fixes, evolutions and new big refactoring operation

### PR DESCRIPTION
**Pull request by dipisoft**
- search for updates: correction of problem in the path of the repository file
- configuration window: reactivation of the "directory listings" tab
- tape edit window: implementation of moving and deleting blocks
- main window: hiding the empty "Edit" menu and several unused context menu options (not coded)
- floppy context menu: implementation of copy/delete/rename and directory output options
- tape context menu: correction of the "rename" option which did not rename the file on the disk but only in the file list
- disk data viewer window: correction to avoid crashes in the event of a damaged floppy disk (there are certainly cases that are not supported)
- list of files: correction of drag&drop blocking after hovering over an item not eligible for drop
- list of files: correction of drag&drop from one block of a tape to another
- display of the content of a tape: bug correction making it impossible to view a block if another with the same name is already displayed
- extraction of blocks from a tape: correction of the bug resulting in systematic crashes
- improved recognition of certain types of files previously categorized as "BASIC program". This concerns Hyperbasic and Teleass sources and many binaries
- instead of the representation of the tapes in the alphabetical index, it is now possible to display them "flat" (addition of an option in the last tab of the configuration window)
- reorganization of context menus: display functions first, launch emulator and finally content modification functions. The option which appears in bold identifies the one which is executed via a double-click.
- modification of the ergonomics of the tree structure:
     - select a program/file or the block of a tape no longer displays its content automatically (you must now double-click it or go through the "view file" option in the context menu)
     - an option has been added in the tape context menu to display the content of all its blocks in a single operation
     - a double-click on a floppy disk or a tape now launches the emulator (for tapes, the machine type pravetz/oric-1/atmos is defined in the configuration window). For floppy disks it is the Atmos which is systematically launched, except for Stratsed floppy disks obviously
     - a double-click on an unknown format floppy disk now displays its content in the "Raw Data Viewer" window
     - double-clicking on a rom displays its content
- modification of the representation of the floppy disks: instead of using different icons for the floppy disks (ft-dos/oric-dos/sedoric/stratsed), it is now the type (master/slave/game) which is differentiated
- modification of the operation of the drag&drop: currently only tapes and blocks of tapes can be copied via drag&drop and they can only be "deposited" on tapes (apart from that of the original drag&drop). Treatments have been added to avoid unsupported operations which, until then, could cause crashes. The nodes "eligible" to be the destination of a drop are marked in green when they are overflown.
- when renaming a file (.dsk or .tap), the extension is added automatically if missing
- change the name of the "Import Text File" window (and the corresponding entry in the "Tools" menu) to "Import Atmos BASIC File" to correspond to its real function.
- "Import Atmos BASIC File" window: the "Import" button can now be clicked if the source/target files have been entered.
- "Import Atmos BASIC File" window always: implementation of the option "Existing tape" which was not and which allows to add a block to an existing tape. The "New disk" and "Existing disk" options not being implemented, they have been deactivated.
- added display of sources generated under Teleass
- tape context menu: addition of an option to launch the emulator with the Pravetz machine
- contextual menu for unknown disks: addition of an option to launch the emulator with sub-options corresponding to each type of machine (Pravetz, Oric-1, Atmos and Telestrat)
- big refacto again, in particular:
     - renaming of forms, prefixed with "frm"
     - renaming of user controls, prefixed with "ctl"
     - renaming of controls (and related events), prefixed with an abbreviation of their type (btn for buttons, lbl for labels, etc.) in order to recognize them more easily in the code and especially to shorten them because certain names were very long
     - delete unused image resources
- adjustment of the tab order of the controls of all windows

### CODE REVIEW

**Comment by dipisoft** [comment]
v2.2.1.0: bug fixes
- in the absence of the configuration file, the app crashed at startup
- when closing the configuration window, the paths of the tapes/disks/roms folders were systematically memorized even when closing the window with the "Cancel" button
- change of the initial folder of the folder selection windows
- change of the selected item when opening the syntax colorization setting window

**Comment by dipisoft** [comment]
v2.3.0.0: adding features
- added the possibility to display the source of Hyperbasic files (thanks to Assinie for his help)
- added support for a new "other files" section (under the Disks, Tapes and ROM's items), whose path or paths are to be configured in the configuration window. This new section can be used to make non-executable files appear in the emulator (orix binaries or others) in order to be able to display the content (request formulated by Jede).
- the "media type" items (Disks, Tapes, ROM's and Other Files) and those of sub-categories (FT-Dos, Sedoric, Stratsed, etc ... as well as the entries in the tapes index) are not now displayed only if they contain items

**Comment by dipisoft** [comment]
Hi Laurent,

I see that you have not yet accepted my last pull requests (the last was in March), so you are still in v2.1 instead of v2.3 on my repo.

I hope you haven't had any health problems (covid or other).

@ +
 
damien.

**Comment by laurentd75** [comment]
Hi Damien,
Sorry for the late reply, I havcen't been looking at this account since the Covid crisis stated :-) 
Anyway, just merged your pull request, many thanks for your useful contributions to this project as usual !!

**Comment by dipisoft** [comment]
No problem, tanks!

**Pull request merged**
